import fs from "fs-extra";
import path from "path";
import ora from "ora";
import chalk from "chalk";
import { execSync } from "child_process";
import eslintConfig from "./esLint.config.js";

// Template path for TypeScript backend
const TemplatePath = path.join(
  path.resolve(),
  "templates",
  "mern",
  "Server",
  "Ts-Backend"
);

class SetupBackendWithTypeScript {
  constructor(projectPath, config, projectName) {
    this.projectPath = projectPath;
    this.config = config;
    this.projectName = projectName;
    this.spinner = ora();
  }

  async createBasicPackageJson() {
    this.spinner.start("Creating package.json...");
    try {
      const packageJsonTemplate_Path = path.join(TemplatePath, "package.json");
      const packageJson = JSON.parse(
        fs.readFileSync(packageJsonTemplate_Path, "utf8")
      );

      packageJson.name = this.projectName;
      packageJson.version = "1.0.0";
      packageJson.description = `${this.projectName} - Generated by Celtrix`;

      fs.writeFileSync(
        path.join(this.projectPath, "package.json"),
        JSON.stringify(packageJson, null, 2)
      );

      this.spinner.succeed("Basic package.json created");
    } catch (error) {
      this.spinner.fail(`Failed to create package.json: ${error.message}`);
      throw error;
    }
  }

  async setupProjectStructure() {
    this.spinner.start("Setting up project structure...");
    try {
      const templateSrcPath = path.join(TemplatePath, "src");
      const templateApp_Path = path.join(TemplatePath, "server.ts");
      fs.copySync(templateSrcPath, path.join(this.projectPath, "src"));
      fs.copySync(templateApp_Path, path.join(this.projectPath, "server.ts"));
      this.spinner.succeed("Project structure created");
    } catch (error) {
      this.spinner.fail(`Failed to setup project structure: ${error.message}`);
      throw error;
    }
  }

  async installDependencies() {
    this.spinner.start("Installing and updating dependencies...");
  
    try {
      process.chdir(this.projectPath);
  
      // Check if pnpm is installed
      try {
        execSync("pnpm --version", { stdio: "ignore" });
      } catch {
        this.spinner.text = "Installing pnpm globally...";
        execSync("npm install -g pnpm", { stdio: "inherit" });
      }
  
      // Check if npm-check-updates is installed
      try {
        execSync("npx npm-check-updates --version", { stdio: "ignore" });
      } catch {
        this.spinner.text = "Installing npm-check-updates globally...";
        execSync("npm install -g npm-check-updates", { stdio: "inherit" });
      }
  
      // Upgrade dependencies using npx
      this.spinner.text = "Upgrading dependencies in package.json...";
      execSync("npx npm-check-updates -u", { stdio: "inherit" });
  
      // Install dependencies with pnpm
      this.spinner.text = "Installing updated dependencies with pnpm...";
      execSync("pnpm install", { stdio: "inherit" });
  
      this.spinner.succeed("Dependencies updated and installed successfully!");
      process.chdir(path.resolve());
    } catch (error) {
      this.spinner.fail(`Dependency installation failed: ${error.message}`);
      try {
        process.chdir(path.resolve());
      } catch {}
      throw error;
    }
  }
  

  async setupEsLintConfig() {
    this.spinner.start("Setting up ESLint configuration...");
    try {
      process.chdir(this.projectPath);

      this.spinner.text = "Installing ESLint dependencies...";
      execSync(
        "pnpm add -D eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint-config-prettier",
        { stdio: "inherit" }
      );

      // Write config files
      this.spinner.text = "Creating ESLint configuration...";
      fs.writeFileSync(
        path.join(this.projectPath, ".eslintrc.json"),
        JSON.stringify(eslintConfig, null, 2)
      );

      fs.writeFileSync(
        path.join(this.projectPath, ".eslintignore"),
        `node_modules\ndist\ncoverage\njest.config.js`
      );

      // Add lint scripts
      const pkgPath = path.join(this.projectPath, "package.json");
      const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
      pkg.scripts = {
        ...pkg.scripts,
        lint: "eslint . --ext .ts",
        "lint:fix": "eslint . --ext .ts --fix",
      };
      fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));

      this.spinner.succeed("ESLint setup completed successfully");
      process.chdir(path.resolve());
    } catch (error) {
      this.spinner.fail(`ESLint setup failed: ${error.message}`);
      try {
        process.chdir(path.resolve());
      } catch {}
      throw error;
    }
  }

  async setupPrettierConfig() {
    this.spinner.start("Setting up Prettier configuration...");
    try {
      const prettierConfig = {
        semi: true,
        trailingComma: "none",
        singleQuote: true,
        printWidth: 80,
        tabWidth: 2,
      };

      fs.writeFileSync(
        path.join(this.projectPath, ".prettierrc"),
        JSON.stringify(prettierConfig, null, 2)
      );

      fs.writeFileSync(
        path.join(this.projectPath, ".prettierignore"),
        `node_modules\ndist\ncoverage\npackage-lock.json\npnpm-lock.yaml\nyarn.lock`
      );

      // Add Prettier to package.json and install
      const pkgPath = path.join(this.projectPath, "package.json");
      const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
      pkg.scripts = {
        ...pkg.scripts,
        format: "prettier --write .",
        "format:check": "prettier --check .",
      };
      pkg.devDependencies = {
        ...pkg.devDependencies,
        prettier: "^2.8.8",
      };
      fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));

      this.spinner.text = "Installing Prettier...";
      execSync("pnpm add -D prettier", { stdio: "inherit" });

      this.spinner.succeed("Prettier configuration completed");
    } catch (error) {
      this.spinner.fail(`Prettier setup failed: ${error.message}`);
      throw error;
    }
  }

  async setUpGitAndHusky() {
    this.spinner.start("Setting up Git and Husky...");
    try {
      process.chdir(this.projectPath);

      if (!fs.existsSync(path.join(this.projectPath, ".git"))) {
        execSync("git init", { stdio: "inherit" });
      }

      this.spinner.text = "Installing Husky...";
      execSync("pnpm add -D husky", { stdio: "inherit" });

      const pkgPath = path.join(this.projectPath, "package.json");
      const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
      pkg.scripts = {
        ...pkg.scripts,
        prepare: "husky install",
      };
      fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));

      this.spinner.text = "Initializing Husky...";
      execSync("pnpm dlx husky install", { stdio: "inherit" });

      const huskyDir = path.join(this.projectPath, ".husky");
      if (!fs.existsSync(huskyDir)) {
        fs.mkdirSync(huskyDir, { recursive: true });
      }

      fs.writeFileSync(path.join(huskyDir, "pre-commit"), `#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm lint
pnpm format
`);
      fs.chmodSync(path.join(huskyDir, "pre-commit"), 0o755);

      fs.writeFileSync(path.join(huskyDir, "pre-push"), `#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm test
`);
      fs.chmodSync(path.join(huskyDir, "pre-push"), 0o755);

      this.spinner.succeed("Git and Husky setup completed");
      process.chdir(path.resolve());
    } catch (error) {
      this.spinner.fail(`Git and Husky setup failed: ${error.message}`);
      try {
        process.chdir(path.resolve());
      } catch {}
      throw error;
    }
  }

  async ConfigureTS() {
    console.log(chalk.blue("\n Setting up TypeScript Backend...\n"));

    try {
      if (!fs.existsSync(this.projectPath)) {
        fs.mkdirSync(this.projectPath, { recursive: true });
      }

      await this.createBasicPackageJson();
      await this.setupProjectStructure();

      if (this.config.setupPrettier) {
        await this.setupPrettierConfig();
      }

      if (this.config.setUpGitAndHusky) {
        await this.setUpGitAndHusky();
      }

      await this.installDependencies();

      if (this.config.setupESLint) {
        await this.setupEsLintConfig();
      }

      console.log(
        chalk.green(
          `\n✅ TypeScript backend setup completed for ${chalk.bold(
            this.projectName
          )
        }\n`
        )
      );
    } catch (error) {
      console.error(chalk.red(`\n❌ Setup failed: ${error.message}\n`));
      throw error;
    }
  }
}

export default SetupBackendWithTypeScript;